version: '3'
services:
  web:
    build: .
    ports:
     - "4000:4000"
    restart: always
    environment:
      - MIX_ENV=prod
      - SECRET_KEY_BASE=jfidasojf9j32jafm34i923uufeaijfdiosajf932u98fjdsajfdsoiaojM0u6S1m6QRfB7QoFROf6g5PT4nZ8uxATtlb6qZLtjHM6Lezb/Iv5j0ei0/3cLx2M
